name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Secret
        env:
          MY_SECRET: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          # Parse the JSON string back to an object
          const myObject = JSON.parse(process.env.MY_SECRET);
          console.log(myObject);
